import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';
import {Header} from "@/components/Header/Header";
import {Suspense} from "react";
import {Loader} from "@/components/Loader/Loader";
import { ResultsProvider } from "@/hooks/resultsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="w-full h-screen flex flex-col items-center bg-gray-950">
          <ResultsProvider>
              <Toaster position={"top-right"}/>
              <Header />
              <Suspense fallback={<Loader />}>
                      {children}
              </Suspense>
          </ResultsProvider>

      </div>
      </body>
    </html>
  );
}
